# Use the official Golang image as the base image
FROM golang:1.22-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download and install the Go dependencies
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go application
RUN go build -o grpc-server .

# EXPOSE PORT
EXPOSE 3001

# Set the entry point for the container
CMD ["./grpc-server"]

# Build the Docker image
# docker build -t jpanaza/so1p2-grpc-server:1.0.0 .
# docker push jpanaza/so1p2-grpc-server:1.0.0