FROM rust:latest as builder
WORKDIR /usr/src/app
COPY . .
RUN cargo build --release
FROM ubuntu:latest
RUN apt-get update && apt-get install -y libssl-dev
COPY --from=builder /usr/src/app/target/release/client /usr/local/bin/client
EXPOSE 8000
CMD ["client"]

# Construir la imagen con mi usuario jpanaza y tag:latest
# docker build -t jpanaza/so1p2-rust-client:2.0.0 .
#Subir la imagen a Docker Hub
# docker push jpanaza/so1p2-rust-client:2.0.0
