FROM rust:1.77.2 as builder

# Create a new empty shell project
RUN USER=root cargo new --bin rust-client
WORKDIR /rust-client

# Copy over your manifests
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# Build only the dependencies
RUN cargo build --release
RUN rm src/*.rs

# Copy your source tree
COPY ./src ./src

# Build for release
RUN cargo build --release

# Our second build stage, this is the final image
FROM rust:1.77.2-slim-buster

COPY --from=builder /rust-client/target/release/rust-client .

CMD ["./rust-client"]








# Construir la imagen con mi usuario jpanaza y tag:latest
# docker build -t jpanaza/so1p2-rust-client:1.0.8 .
#Subir la imagen a Docker Hub
# docker push jpanaza/so1p2-rust-client:1.0.8
