version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - my_network
    ports:
      - 5055:3306
  adminer:
    image: adminer
    restart: always
    networks:
      - my_network
    ports:
      - 8080:8080
networks:
  my_network: