version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - my_network
    ports:
      - 5055:3306
  adminer:
    image: adminer
    restart: always
    networks:
      - my_network
    ports:
      - 8080:8080
  backend:
    image: backend_so1_p1
    container_name: API_Signal
    privileged: true
    restart: always
    volumes:
      - type: bind
        source: /proc
        target: /proc
    networks:
      - my_network
    ports:
      - 8000:8000
    
networks:
  my_network: