# Usa la imagen oficial de Rust como base
FROM rust:latest as builder

# Crea un directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia los archivos de tu aplicación al contenedor
COPY . .

# Compila la aplicación
RUN cargo build --release

# Crea una nueva imagen ligera
FROM ubuntu:latest

# Instala las dependencias necesarias
RUN apt-get update && apt-get install -y libssl-dev

# Copia el binario compilado desde la imagen de compilación a la imagen final
COPY --from=builder /usr/src/app/target/release/server /usr/local/bin/server

# Exponer el puerto que utiliza tu aplicación
EXPOSE 8080

# Comando para ejecutar tu aplicación cuando se inicie el contenedor
CMD ["server"]


# Construir la imagen con mi usuario jpanaza y tag:latest
# docker build -t jpanaza/so1p2-rust-server:2.0.0 .
# Subir la imagen a Docker Hub
# docker push jpanaza/so1p2-rust-server:2.0.0