# Stage 1: Construir la aplicación React
FROM node:18.18.2-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: Servir la aplicación con Nginx
FROM nginx:latest

# Copiar el archivo de configuración personalizado de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Eliminar el archivo de configuración predeterminado
RUN rm /etc/nginx/conf.d/default.conf

# Copiar la aplicación construida de la etapa anterior
COPY --from=build /app/build /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80

# Comando para iniciar Nginx en primer plano
CMD ["nginx", "-g", "daemon off;"]



#Comandos de docker
#docker build -t frontend_so1_p1 .
#docker run -p 80:80 frontend_so1_p1