version: '3'

services:
  mongo:
    image: mongo
    container_name: 'MongoDB'
    restart: always
    volumes:
      - volume_mongo:/var/lib/mongo
    ports:
      - "27017:27017"
    backend:
      image: 'backendt2so1'
      container_name: 'BackendNodeJS'
      restart: always
      ports:
        - "5000:5000"
    frontend:
      image: 'frontendt2so1'
      container_name: 'FrontendReact'
      restart: always
      ports:
        - "3000:3000"
volumes:
  volume_mongo: