version: '3.1'

services:
  mongo:
    image: mongo
    container_name: 'MongoDB'
    restart: always
    volumes:
      - volume_mongo:/data/db
    networks:
      - my_network
    ports:
      - "27017:27017"
  backend:
    image: 'backendt2so1'
    container_name: 'BackendNodeJS'
    restart: always
    networks:
      - my_network
    ports:
      - "5000:5000"
  frontend:
    image: 'frontendt2so1'
    container_name: 'FrontendReact'
    networks:
      - my_network
    ports:
      - "3000:3000"
volumes:
  volume_mongo:

networks:
  my_network: