# Usa una imagen base con Node.js y Yarn
FROM node:21.6.2-alpine

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de configuración de Yarn
COPY package.json yarn.lock ./

# Instala las dependencias utilizando Yarn
RUN yarn install

# Copia el resto de los archivos de la aplicación
COPY . .

# Compila la aplicación Vue.js
RUN yarn build

# Exponer el puerto de la aplicación si es necesario (ajusta el puerto según tu aplicación)
EXPOSE 8080

# Comando para iniciar la aplicación (ajusta según sea necesario)
CMD ["yarn", "serve"]

# Construir la imagen con mi usuario jpanaza y tag:latest
# docker build -t jpanaza/so1p2-web-front:1.0.0 .
# Subir la imagen a Docker Hub
# docker push jpanaza/so1p2-web-front:1.0.0