# Etapa de compilación
FROM node:21.6.2-alpine as build

# Establecer el directorio de trabajo
WORKDIR /usr/local/app

# Copiar archivos de configuración de Yarn
COPY package.json yarn.lock ./

# Instalar dependencias utilizando Yarn
RUN yarn install

# Copiar el resto de los archivos de la aplicación
COPY . .

# Compilar la aplicación Vue.js
RUN yarn build --prod

# Etapa de producción
FROM nginx:alpine

# Copiar la aplicación compilada de la etapa de compilación a la imagen de Nginx
COPY --from=build /usr/local/app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf 

# Exponer el puerto 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

# Construir la imagen con mi usuario jpanaza y tag:latest
# docker build --no-cache=true -t jpanaza/so1p2-web-front:2.0.2 .
# Subir la imagen a Docker Hub
# docker push jpanaza/so1p2-web-front:2.0.2