FROM node:18.16.2-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]

# Notes
# docker build -t frontendt2so1
# docker run -p 3000:3000 frontendt2so1