# Usa una imagen base con Node.js y Alpine Linux
FROM node:21.6.2-alpine

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el resto de los archivos de la aplicación
COPY . .

RUN npm install --production


# Expone el puerto en el que corre la API (ajusta según sea necesario)
EXPOSE 5000

# Define el comando de inicio de la API
CMD ["node", "src/main.js"]

# Construye la imagen con el comando:
# docker build --no-cache=true -t jpanaza/so1p2-web-api:2.0.0 .
# Sube la imagen a Docker Hub con el comando:
# docker push jpanaza/so1p2-web-api:2.0.0