apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka
  name: consumer-deployment
spec:
  selector:
    matchLabels:
      app: consumer-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer-deployment
    spec:
      containers:
      - name: consumer-deployment
        image: jpanaza/so1p2-consumer:1.0.5
        resources:
          limits:
            memory: "128Mi"
            cpu: "20m"
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: kafka
  name: consumer-hpa
spec:
  selector:
  template:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
